### ISSUE TITLE
run and dataset

### ISSUE THREAD

**Issue by qianbudiao6** [manthanthakker/speakerIdentification#2]
Hello, I am currently researching speaker recognition. I think your code is very valuable. I want to run it for learning. How can I run this code? Is there such a tutorial? In addition, can I share a link to a speech library to implement this code? thanks!

**Comment by manthanthakker** [comment]
Hello, 
First of all, I am glad that you found the code to be valuable and I hope it helps in your research. I implemented a Neural network in matlab in the year 2016 as part of our thesis project. I am re-working on this project and found ready-made libraries (Keras and Tensorflow) to implement Neural networks to be much easier and have included in the project. You can run it as a standard python code or you can run it using Ipython notebooks. Documentation for keras library: [Keras](https://keras.io/). If you have any more questions, feel free to contact me on manthanthakker40@gmail.com
